In [65]:
import os
import re

from transformers import pipeline
from transformers import AutoModelForSequenceClassification
from transformers import TFAutoModelForSequenceClassification
from transformers import AutoTokenizer, AutoConfig
import numpy as np
from scipy.special import softmax

import spacy

import pandas as pd

import math

extract name

In [66]:
#names
#names count

def extract_name(text):
  name_ls = []
  names_count = 0
  matches = re.findall(r'my name is (\w+) (\w+)', text, re.IGNORECASE)
  for match in matches:
    name_ls.append(match)
    names_count += 1
    
  return name_ls, names_count

extract keywords

In [67]:
#parking
#affordability
#community
#total words

def extract_keywords(text):
  words = text.split()
  words_count = len(words)

  word_hash = {}
  for word in words:
    if word not in word_hash:
        word_hash[word] = 1
    else:
        word_hash[word] += 1

  parking_count = 0
  if "parking" in word_hash:
     parking_count = word_hash["parking"]
  if "Parking" in word_hash:
     parking_count = word_hash["Parking"]
 

  affordable_count = 0
  if "affordability" in word_hash:
     affordable_count = word_hash["affordability"]
  if "affordable" in word_hash:
     affordable_count += word_hash["affordable"]
  if "Affordability" in word_hash:
     affordable_count = word_hash["Affordability"]
  if "Affordable" in word_hash:
     affordable_count += word_hash["Affordable"]
     

  community_count = 0
  if "community" in word_hash:
     community_count = word_hash["community"]
  if "communities" in word_hash:
     community_count += word_hash["communities"]
  if "Community" in word_hash:
     community_count = word_hash["Community"]
  if "Communities" in word_hash:
     community_count += word_hash["Communities"]



  
  return words_count, parking_count, affordable_count, community_count

sentiment

In [68]:
#sentiment
MODEL = f"cardiffnlp/twitter-roberta-base-sentiment-latest"


tokenizer = AutoTokenizer.from_pretrained(MODEL)
config = AutoConfig.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

def get_sentiment(text):
  encoded_input = tokenizer(text, return_tensors='pt')
  if encoded_input['input_ids'].size(1) > 500:
    return 0.5, 0.5, 0.5
  output = model(**encoded_input)
  scores = output[0][0].detach().numpy()
  scores = softmax(scores)

  return scores[0], scores[1], scores[2]

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

word count

In [69]:
#text minus stop words
#text minus stop word count 

def remove_stop_words(text):
  words = text.split()
  non_stop_words_count = 0
  nlp = spacy.load("en_core_web_sm")
  stop_words = spacy.lang.en.stop_words.STOP_WORDS
  for i in range(len(words)):
     if words[i] not in stop_words:
        non_stop_words_count += 1
  return non_stop_words_count

merge

In [70]:
cleaned_hyperlinks_df = pd.read_csv("cleaned_hyperlinks.csv")
case_to_df = {}

collapsed_df = cleaned_hyperlinks_df.groupby(['clean_file_name', 'case_name'])['audio_file_name'].agg(list).reset_index()


df = pd.DataFrame(columns=['case_name', 'CEQA', 'names', 'names_count', 'parking_mentions', 'affordability_mentions', 'community_mentions', 'num_words', 'num_nonstopgap_words', 'sentiment_pos', 'sentiment_neg', 'sentiment_neutral', 'date', 'area', 'txt_file_name'])

In [71]:
collapsed_df

,clean_file_name,case_name,audio_file_name
0,01-05-10audio,01DepartmentalRepor,[01-05-10audio_01DepartmentalReport]
1,01-05-10audio,02CommissionBusines,[01-05-10audio_02CommissionBusiness]
2,01-05-10audio,03ZA09-2885&04ZA09-2886,"[01-05-10audio_03ZA09-2885_04ZA09-2886a, 01-05..."
3,01-05-10audio,04ZA09-2886,[01-05-10audio_04ZA09-2886]
4,01-05-10audio,05APCW10-657,[01-05-10audio_05APCW10-657]
...,...,...,...
2677,WLA12-05-12audio,04PublicCommentPerio,[WLA12-05-12audio_04PublicCommentPeriod]
2678,WLA12-07-11audio,01DepartmentalRepor,[WLA12-07-11audio_01DepartmentalReport]
2679,WLA12-07-11audio,02CommissionBusines,[WLA12-07-11audio_02CommissionBusiness]
2680,WLA12-07-11audio,03ZA11-1481,[WLA12-07-11audio_03ZA11-1481]
2681,WLA12-07-11audio,04DIR10-2280,[WLA12-07-11audio_04DIR10-2280]

In [72]:
# filtered_rows = cleaned_hyperlinks_df[(cleaned_hyperlinks_df['clean_file_name'] == "07-12-2012audio") & (cleaned_hyperlinks_df['case_name'] == "01DirectorsRepor")]

# date = filtered_rows.loc[0, 'hearing_date']
# area = filtered_rows.loc[0, 'area']
# area
# date

In [73]:
#merge txt
#load in df
def get_date_location(clean_file_name, case_name):

  filtered_rows = cleaned_hyperlinks_df[(cleaned_hyperlinks_df['clean_file_name'] == clean_file_name) & (cleaned_hyperlinks_df['case_name'] == case_name)]

  date = filtered_rows.iloc[0]['hearing_date']
  area = filtered_rows.iloc[0]['area']

  return date, area


def get_ceqa(clean_file_name, case_name):
  filtered_rows = cleaned_hyperlinks_df[(cleaned_hyperlinks_df['clean_file_name'] == clean_file_name) & (cleaned_hyperlinks_df['case_name'] == case_name)]
  text_vals = filtered_rows['Text'].tolist()

  pattern = r"CEQA:\s*([\w-]+)"

  for text in text_vals:
    match = re.search(pattern, str(text))

    if match:
      code = match.group(1)
      return code
 
  
  return np.NaN

def split_text(text, chunk_size=1500):
    # words = text.split()  # Split the text into individual words
    # chunks = []
    # current_chunk = []  # Initialize an empty list to hold the words in the current chunk
    # word_count = 0  # Initialize a counter for the number of words in the current chunk
    
    # # Iterate over the words in the text
    # for word in words:
    #     current_chunk.append(word)  # Add the word to the current chunk
    #     word_count += 1  # Increment the word count
        
    #     # If the word count reaches the chunk size or if it's the last word
    #     if word_count == chunk_size or word == words[-1]:
    #         # Add the current chunk to the list of chunks
    #         chunks.append(' '.join(current_chunk))
    #         current_chunk = []  # Reset the current chunk
    #         word_count = 0  # Reset the word count
    chunks = []
    for i in range(0, len(text), chunk_size):
        chunk = text[i:i+chunk_size]
        chunks.append(chunk)
    
    return chunks


for index, row in collapsed_df.iterrows():
  file_names = row['audio_file_name']
  clean_file_name = row['clean_file_name']
  case_name = row['case_name']

  ceqa = get_ceqa(clean_file_name, case_name)
  date, area = get_date_location(clean_file_name, case_name)
  text = " "
  for file in file_names:
    file_name = 'txt/' + file + '.txt'
    if os.path.exists(file_name):
      with open(file_name, 'r') as file:
        this_file_text = file.read()
        text += this_file_text
  print(file_name)
  name_ls, names_count = extract_name(text)
  words_count, parking_count, affordable_count, community_count = extract_keywords(text)
  # if words_count > 300:
  #   length = len(text)
  #   negative, neutral, pos = get_sentiment(text[0:500])
  #   all_vals_array = np.array([negative, neutral, pos])
  #   for i in range(500, length, 500):
  #     negative, neutral, pos = get_sentiment(text)
  #     this_vals_array = np.array([negative, neutral, pos])
  #     all_vals_array = np.vstack((all_vals_array, this_vals_array))
  #   means_array = np.mean(all_vals_array, axis=1)
  #   negative, neutral, pos = means_array[0], means_array[1], means_array[2]
  
  chunks = split_text(text)
  negative_ls = []
  neutral_ls = []
  pos_ls = []
  for i in range(len(chunks)):
    # encoded_input = tokenizer(chunks[i], return_tensors='pt')
    # output = model(**encoded_input)
    # scores = output[0][0].detach().numpy()
    # scores = softmax(scores)

    # negative, neutral, pos = scores[0], scores[1], scores[2]
    # print(len)
    negative, neutral, pos = get_sentiment(chunks[i])
    negative_ls.append(negative)
    neutral_ls.append(neutral)
    pos_ls.append(pos)


  negative = np.mean(negative_ls)
  neutral = np.mean(neutral_ls)
  pos = np.mean(pos_ls)


  




  file_name_save = clean_file_name+case_name+".txt"
  file_name_save = file_name.replace(" ", "")
  # else:
  #   negative, neutral, pos = get_sentiment(text)
  non_stop_words_count = remove_stop_words(text)
      
  new_row = [case_name, ceqa, name_ls, names_count, parking_count, affordable_count, community_count, words_count, non_stop_words_count, pos, negative, neutral, date, area, file_name_save]
  #df = df.append(pd.Series(new_row, index=df.columns), ignore_index=True)
  df.loc[len(df)] = new_row
  df.to_csv('cases.tsv', sep='\t',index=False)

txt/01-05-10audio_01DepartmentalReport.txt
txt/01-05-10audio_02CommissionBusiness.txt
txt/01-05-10audio_03ZA09-2885_04ZA09-2886b.txt
txt/01-05-10audio_04ZA09-2886.txt
txt/01-05-10audio_05APCW10-657.txt
txt/01-05-10audio_06APCW10-2130.txt
txt/01-05-10audio_07ZA07-5584b.txt
txt/01-09-13audio_01DepartmentalReport.txt
txt/01-09-13audio_02CommissionBusiness.txt
txt/01-09-13audio_03APCE12-1723b.txt
txt/01-09-13audio_04PublicCommentPeriod.txt
txt/01-10-2017audio_1 DirRpt.txt
txt/01-10-2017audio_2 CommBus.txt
txt/01-10-2017audio_3 NCP.txt
txt/01-10-2017audio_4 VTT-72513.txt
txt/01-10-2017audio_5 PubCom.txt
txt/01-11-2011audio_01DirectorsReport.txt
txt/01-11-2011audio_02CommissionBusiness.txt
txt/01-11-2011audio_03ZA08-3851.txt
txt/01-11-2011audio_04ZA09-4164b.txt
txt/01-11-2011audio_05ZA09-2116.txt
txt/01-11-2011audio_06ZA09-1185.txt
txt/01-11-2011audio_07DIR10-1338b.txt
txt/01-11-2017audio_1 DirRpt.txt
txt/01-11-2017audio_2 CommBus.txt
txt/01-11-2017audio_3 NCP.txt
txt/01-11-2017audio_4 ZA-2015-1109.txt
txt/01-11-2017audio_5 ZA-2016-1638.txt
txt/01-11-2017audio_6 VTT-74164.txt
txt/01-11-2017audio_7 VTT-74301.txt
txt/01-11-2017audio_8 PubCom.txt
txt/01-12-17audio_1 Dir Rpt.txt
txt/01-12-17audio_2 CommBus.txt
txt/01-12-17audio_3 NCP.txt
txt/01-12-17audio_4 PubCom.txt
txt/01-12-17audio_5a CPC-2016-3367.txt
txt/01-12-17audio_5b CPC-2016-1958.txt
txt/01-12-17audio_6 CPC-2014-2947.txt
txt/01-12-17audio_7 CPC-2016-1735.txt
txt/01-12-2012audio_01DirectorsReport.txt
txt/01-12-2012audio_02commissionBusiness.txt
txt/01-12-2012audio_03PublicCommentPeriod.txt
txt/01-12-2012audio_04CPC07-3036_CPC08-3125c.txt
txt/01-12-2012audio_05CPC07-2622.txt
txt/01-12-2012audio_06CPC11-1770b.txt
txt/01-12-2012audio_07CPC11-2043.txt
txt/01-12-2012audio_08CPC09-456c.txt
txt/01-13-2011audio_01DirectorsReportb.txt
txt/01-13-2011audio_02CommissionBusiness.txt
txt/01-13-2011audio_03PublicCommentPeriod.txt
txt/01-13-2011audio_04CPC06-10241h.txt
txt/01-13-2011audio_05CPC10-1929.txt
txt/01-13-2011audio_06CPC10-1572b.txt
txt/01-13-2016audio_1 DirRpt.txt
txt/01-13-2016audio_2 CommBus.txt
txt/01-13-2016audio_3 AA-2015-777-PMLA-SL-1A.txt
txt/01-13-2016audio_4 PubCom.txt
txt/01-14-2016audio_1 DirRpt.txt
txt/01-14-2016audio_2 CommBus.txt
txt/01-14-2016audio_3 PS-1430-1A.txt
txt/01-14-2016audio_4 AA-2015-1726-PMLA-1A.txt
txt/01-14-2016audio_5 PubCom.txt
txt/01-17-2017audio_1 DirRpt.txt
txt/01-17-2017audio_2 CommBus.txt
txt/01-17-2017audio_3 NCP.txt
txt/01-17-2017audio_4 DIR-2016-3329.txt
txt/01-17-2017audio_5 PubCom.txt
txt/01-18-2017audio_repaired_1 DirRpt.txt
txt/01-18-2017audio_repaired_2 CommBus.txt
txt/01-18-2017audio_repaired_3 NCP.txt
txt/01-18-2017audio_repaired_4 AA-2016-315.txt
txt/01-18-2017audio_repaired_5-6 ZA-2014-3182 and ZA-2014-3186.txt
txt/01-18-2017audio_repaired_7 ZA-2016-1265.txt
txt/01-18-2017audio_repaired_8 PubCom.txt
txt/01-19-11audio_01DepartmentalReport.txt
txt/01-19-11audio_02CommissionBusiness.txt
txt/01-19-11audio_03APCW10-800b.txt
txt/01-19-11audio_04APCW10-2130.txt
txt/01-22-2013audio_01DirectorsReport.txt
txt/01-22-2013audio_02CommissionBusiness.txt
txt/01-22-2013audio_03ZA12-598c.txt
txt/01-22-2013audio_04ZA11-3280b.txt
txt/01-22-2013audio_05CPC11-2103c.txt
txt/01-24-2013audio_01DirectorsReportb.txt
txt/01-24-2013audio_02CommissionBusiness.txt
txt/01-24-2013audio_03PublicCommentPeriod.txt
txt/01-24-2013audio_04CPC12-1214b.txt
txt/01-24-2013audio_05CPC09-3271.txt
txt/01-24-2017audio_1 DirRpt.txt
txt/01-24-2017audio_2 CommBus.txt
txt/01-24-2017audio_3 NCP.txt
txt/01-24-2017audio_4 TT-73626.txt
txt/01-24-2017audio_5 PubCom.txt
txt/01-25-2011audio_01DirectorsReport.txt
txt/01-25-2011audio_02CommissionBusiness.txt
txt/01-25-2011audio_03ZA10-1665.txt
txt/01-25-2011audio_04PublicCommentPeriod.txt
txt/01-25-2017audio_1 DirRpt.txt
txt/01-25-2017audio_2 CommBus.txt
txt/01-25-2017audio_3 NCP.txt
txt/01-25-2017audio_4 VTT-74301+PubCom.txt
txt/01-26-17audio_10-11 CPC-2016-4382 and CPC-2016-3632.txt
txt/01-26-17audio_12 Civic Center Master Plan.txt
txt/01-26-17audio_8 CPC-2016-270.txt
txt/01-26-17audio_9 CPC-2016-2881.txt
txt/01-26-2012audio_01DirectorsReport.txt
txt/01-26-2012audio_02CommissionBusiness.txt
txt/01-26-2012audio_03PublicCommentPeriod.txt
txt/01-26-2012audio_04CPC11-1880c.txt
txt/01-26-2012audio_05SpecialIteme.txt
txt/01-26-2012audio_SpecialItemCouncilmemberStatement.txt
txt/01-27-2011audio_01DepartmentalReport.txt
txt/01-27-2011audio_02CommissionBusiness.txt
txt/01-27-2011audio_03ZA10-1104b.txt
txt/01-27-2011audio_04ZA10-2328b.txt
txt/01-27-2011audio_05APCSV08-4285.txt
txt/01-27-2011audio1_01DirectorsReport.txt
txt/01-27-2011audio1_02CommissionBusiness.txt
txt/01-27-2011audio1_03PublicCommentPeriod.txt
txt/01-27-2011audio1_04CPC10-319d.txt
txt/01-27-2011audio1_05CPC10-1296.txt
txt/02-01-2017audio_1 DirRpt.txt
txt/02-01-2017audio_2 CommBus.txt
txt/02-01-2017audio_3 NCP.txt
txt/02-01-2017audio_4 DIR-2016-2302.txt
txt/02-01-2017audio_5 DIR-2014-4577.txt
txt/02-01-2017audio_6 ZA-2014-1500.txt
txt/02-01-2017audio_7 PubCom.txt
txt/02-02-2017audio_1 DirRpt.txt
txt/02-02-2017audio_2 CommBus.txt
txt/02-02-2017audio_3 NCP.txt
txt/02-02-2017audio_4 ZA-2016-1485.txt
txt/02-02-2017audio_5 ZA-2016-1555.txt
txt/02-02-2017audio_6 PubCom.txt
txt/02-09-11audio_01CommissionBusiness.txt
txt/02-09-11audio_02ZA10-2038e.txt
txt/02-09-17audio_1 DirRpt.txt
txt/02-09-17audio_2 CommBus.txt
txt/02-09-17audio_3 NCP.txt
txt/02-09-17audio_4 PubCom.txt
txt/02-09-17audio_5a CPC-2016-2466 AND 5b CPC-2016-3044.txt
txt/02-09-17audio_6 VTT-72928.txt
txt/02-09-17audio_7 VTT-73981 and 8 CPC-2016-341.txt
txt/02-09-2012audio_01DirectorsReport.txt
txt/02-09-2012audio_02CommissionBusiness.txt
txt/02-09-2012audio_03PublicCommentPeriod.txt
txt/02-09-2012audio_04DIR09-2065.txt
txt/02-09-2012audio_05CPC07-3036_CPC08-3125c.txt
txt/02-10-2011audio_01DirectorsReport.txt
txt/02-10-2011audio_02CommissionBusiness.txt
txt/02-10-2011audio_03PublicCommentPeriod.txt
txt/02-10-2011audio_04CPC10-652.txt
txt/02-10-2011audio_05CPC10-1945b.txt
txt/02-10-2011audio_06CPC06-10241c.txt
txt/02-10-2011audio_07CPC10-2841.txt
txt/02-10-2011audio_08CPC09-800d.txt
txt/02-10-2016audio_1 DeptRpt.txt
txt/02-10-2016audio_10 DIR-2014-1941-SPP-1A.txt
txt/02-10-2016audio_11 DIR-2014-1942-SPP-1A.txt
txt/02-10-2016audio_12 DIR-2014-2243-SPP-1A.txt
txt/02-10-2016audio_13 PubCom.txt
txt/02-10-2016audio_2 CommBus.txt
txt/02-10-2016audio_3 DIR-2015-1173-SPP-1A.txt
txt/02-10-2016audio_4 DIR-2014-1705-SPP-1A.txt
txt/02-10-2016audio_5 DIR-2014-1927-SPP-1A.txt
txt/02-10-2016audio_6 DIR-2014-1934-SPP-1A.txt
txt/02-10-2016audio_7 DIR-2014-1938-SPP-1A.txt
txt/02-10-2016audio_8 DIR-2014-1939-SPP-1A.txt
txt/02-10-2016audio_9 DIR-2014-1940-SPP-1A.txt
txt/02-14-2012audio_01DirectorsReport.txt
txt/02-14-2012audio_02CommissionBusiness.txt
txt/02-14-2012audio_03APCC11-1621.txt
txt/02-14-2012audio_04ZA95-282c.txt
txt/02-14-2012audio_05ZA09-3688b.txt
txt/02-14-2012audio_06PublicCommentPeriod.txt
txt/02-14-2013audio_01DirectorsReport.txt
txt/02-14-2013audio_02CommissionBusiness.txt
txt/02-14-2013audio_03CPC12-579b.txt
txt/02-14-2013audio_04CPC12-1737.txt
txt/02-14-2013audio_05CPC12-3357d.txt
txt/02-14-2017audio_1 DirRpt.txt
txt/02-14-2017audio_2 CommBus.txt
txt/02-14-2017audio_3 NCP.txt
txt/02-14-2017audio_4 VTT-73292.txt
txt/02-14-2017audio_5 ZA-2016-201.txt
txt/02-14-2017audio_6 DIR-2015-2615.txt
txt/02-14-2017audio_7 APCC-2015-3286.txt
txt/02-14-2017audio_8 APCC-2016-3327.txt
txt/02-14-2017audio_9 PubCom.txt
txt/02-15-2017audio_1 DirRpt.txt
txt/02-15-2017audio_2 CommBus.txt
txt/02-15-2017audio_3 NCP.txt
txt/02-15-2017audio_4 DIR-2013-2966.txt
txt/02-15-2017audio_5 ZA-2016-1587.txt
txt/02-15-2017audio_6 ZA-2016-94.txt
txt/02-15-2017audio_7 PubCom.txt
txt/02-16-2017audio_1 DirRpt.txt
txt/02-16-2017audio_2 CommBus.txt
txt/02-16-2017audio_3 NCP.txt
txt/02-16-2017audio_4 DIR-2016-1555.txt
txt/02-16-2017audio_5 APCNV-2015-2763.txt
txt/02-16-2017audio_6 PubCom.txt
txt/02-21-2017audio_1 DirRpt.txt
txt/02-21-2017audio_2 CommBus.txt
txt/02-21-2017audio_3 NCP.txt
txt/02-21-2017audio_4 DIR-2016-3993.txt
txt/02-21-2017audio_5 PubComm.txt
txt/02-22-12audio_01DepartmentalReport.txt
txt/02-22-12audio_02CommissionBusiness.txt
txt/02-22-12audio_03ZA10-28.txt
txt/02-22-12audio_04ZA11-2241.txt
txt/02-22-2011audio_01DirectorsReport.txt
txt/02-22-2011audio_02CommissionBusiness.txt
txt/02-22-2011audio_03ZA10-2067.txt
txt/02-22-2011audio_04APCC10-1884.txt
txt/02-22-2011audio_05VTT-70608.txt
txt/02-22-2017audio_1 DirRpt.txt
txt/02-22-2017audio_2 CommBus.txt
txt/02-22-2017audio_3 NCP.txt
txt/02-22-2017audio_4 ZA-2016-1745.txt
txt/02-22-2017audio_5 PubCom.txt
txt/02-23-17audio_1 DirRpt.txt
txt/02-23-17audio_2 CommBus.txt
txt/02-23-17audio_3 NCP.txt
txt/02-23-17audio_4 PubCom.txt
txt/02-23-17audio_5a CPC-2015-4613.txt
txt/02-23-17audio_5b CPC-2016-3247.txt
txt/02-23-17audio_6 VTT-73427 and 7 CPC-2004-7308.txt
txt/02-23-17audio_8 CPC-2016-3431.txt
txt/02-23-2016_TRACK1.txt
txt/02-24-2011audio_01DirectorsReport.txt
txt/02-24-2011audio_02PublicCommentPeriod.txt
txt/02-24-2011audio_03CPC10-817.txt
txt/02-24-2011audio_04CPC09-2597.txt
txt/02-24-2011audio_05CPC09-3592.txt
txt/02-24-2011audio2_01CommissionBusiness.txt
txt/02-24-2011audio2_02ZA10-407.txt
txt/02-24-2011audio2_03DepartmentalReport.txt
txt/02-24-2016audio_1 Dept Rpt.txt
txt/02-24-2016audio_2 CommBus.txt
txt/02-24-2016audio_3 ZA-2014-3054-ZAD-1A.txt
txt/02-24-2016audio_4 PubCom.txt
txt/02-25-2016_TRACK1.txt
txt/02-25-2016_TRACK2.txt
txt/02-25-2016_TRACK3.txt
txt/02-25-2016_TRACK4.txt
txt/02-26-2013audio_01DirectorsReport.txt
txt/02-26-2013audio_02CommissionBusiness.txt
txt/02-26-2013audio_03ZA12-1086.txt
txt/02-26-2013audio_04DIR12-1353d.txt
txt/02-26-2013audio_05PublicCommentPeriod.txt
txt/02-28-2012audio_01DirectorsReport.txt
txt/02-28-2012audio_02CommissionBusiness.txt
txt/02-28-2012audio_03DIR11-1919b.txt
txt/02-28-2012audio_04PublicCommentPeriod.txt
txt/02-28-2013audio_01DirectorsReport.txt
txt/02-28-2013audio_02CommissionBusiness.txt
txt/02-28-2013audio_03PublicCommentPeriod.txt
txt/02-28-2013audio_04CPC09-837.txt
txt/02-28-2013audio_05CPC08-4604g.txt
txt/02-28-2017audio_1 DirRpt.txt
txt/02-28-2017audio_2 Comm Bus.txt
txt/02-28-2017audio_2 CommBus.txt
txt/02-28-2017audio_3 NCP.txt
txt/02-28-2017audio_4 AA-2016-2034.txt
txt/02-28-2017audio_5 APCC-2015-3286-CU-SPR.txt
txt/02-28-2017audio_6 DIR-2015-2615.txt
txt/02-28-2017audio_7 AA-2016-936.txt
txt/02-28-2017audio_8 PubCom.txt
txt/03-01-2016_TRACK1.txt
txt/03-01-2016_TRACK2.txt
txt/03-01-2016_TRACK3.txt
txt/03-01-2016_TRACK4.txt
txt/03-01-2017audio_1 DirRpt.txt
txt/03-01-2017audio_2 CommBus.txt
txt/03-01-2017audio_3 NCP.txt
txt/03-01-2017audio_4 APCW-2014-3157.txt
txt/03-01-2017audio_5 APCS-2014-2654.txt
txt/03-01-2017audio_6 ZA-2011-1424.txt
txt/03-01-2017audio_7 PubCom.txt
txt/03-02-11audio1_01DepartmentalReport.txt
txt/03-02-11audio1_02CommissionBusiness.txt
txt/03-02-11audio1_03DIR08-5036.txt
txt/03-03-2016_TRACK1.txt
txt/03-03-2016_TRACK2.txt
txt/03-03-2016_TRACK3.txt
txt/03-03-2016_TRACK4.txt
txt/03-08-2012audio_01DirectorsReport.txt
txt/03-08-2012audio_02CommissionBusiness.txt
txt/03-08-2012audio_03CPC09-3210.txt
txt/03-08-2012audio_04CPC11-1920.txt
txt/03-08-2012audio_05CPC10-31c.txt
txt/03-08-2012audio_06CPC08-1552_CPC08-1553b.txt
txt/03-09-17audio_1 DirRpt.txt
txt/03-09-17audio_2 CommBus.txt
txt/03-09-17audio_3 NCP.txt
txt/03-09-17audio_4 PubCom.txt
txt/03-09-17audio_5a CPC-2016-3064.txt
txt/03-09-17audio_6 CPC-2016-4216.txt
txt/03-10-2011audio_01DirectorsReport.txt
txt/03-10-2011audio_02CommissionBusiness.txt
txt/03-10-2011audio_03PublicCommentPeriod.txt
txt/03-10-2011audio_04CPC10-2221.txt
txt/03-10-2011audio_05CPC09-3488c.txt
txt/03-10-2011audio_06CPC10-2722.txt
txt/03-12-2013audio_01DirectorsReport.txt
txt/03-12-2013audio_02CommissionBusiness.txt
txt/03-12-2013audio_03ZA12-1517.txt
txt/03-12-2013audio_04ZA12-1227d.txt
txt/03-12-2013audio_05PublicCommentPeriod.txt
txt/03-14-12audio_01DepartmentalReport.txt
txt/03-14-12audio_02CommissionBusiness.txt
txt/03-14-12audio_03ZA11-2241b.txt
txt/03-14-12audio_04ZA10-28b.txt
txt/03-14-2013audio_01DirectorsReport.txt
txt/03-14-2013audio_02CommissionBusiness.txt
txt/03-14-2013audio_03PublicCommentPeriod.txt
txt/03-14-2013audio_CPC09-1557h.txt
txt/03-15-2011audio_03ZA09-1836a.txt
txt/03-15-2011audio_04ZA09-1836b.txt
txt/03-15-2017audio_1 DirRpt.txt
txt/03-15-2017audio_2 CommBus.txt
txt/03-15-2017audio_3 NCP.txt
txt/03-15-2017audio_4 ZA-2014-3182.txt
txt/03-15-2017audio_5 ZA-2014-3186.txt
txt/03-15-2017audio_6 ZA-2015-2404.txt
txt/03-15-2017audio_7 ZA-2016-1587.txt
txt/03-15-2017audio_8 PubCom.txt
txt/03-16-11audio_01DepartmentalReport.txt
txt/03-16-11audio_02CommissionBusiness.txt
txt/03-16-11audio_03APCW10-2349.txt
txt/03-16-11audio_04APCW09-3151.txt
txt/03-17-2016_TRACK1.txt
txt/03-17-2016_TRACK2.txt
txt/03-17-2016_TRACK3.txt
txt/03-17-2016_TRACK4.txt
txt/03-17-2016_TRACK5.txt
txt/03-17-2016_TRACK6.txt
txt/03-22-2011audio_01DirectorsReport.txt
txt/03-22-2011audio_02CommissionBusiness.txt
txt/03-22-2011audio_03DIR10-359.txt
txt/03-22-2011audio_04ZA08-3851b.txt
txt/03-22-2011audio_05ZA10-2067b.txt
txt/03-22-2011audio_06DIR10-1983c.txt
txt/03-22-2011audio_07DIR09-2189.txt
txt/03-22-2012audio_01DirectorsReport.txt
txt/03-22-2012audio_02CommissionBusiness.txt
txt/03-22-2012audio_03PublicCommentPeriod.txt
txt/03-22-2012audio_04CPC11-1187d.txt
txt/03-22-2017audio_1 DirRpt.txt
txt/03-22-2017audio_2 CommBus.txt
txt/03-22-2017audio_3 NCP.txt
txt/03-22-2017audio_4 Dir-2016-3168.txt
txt/03-22-2017audio_5 DIR-2015-1187.txt
txt/03-22-2017audio_6 PubCom.txt
txt/03-23-2016audio_1 DeptRpt.txt
txt/03-23-2016audio_2 CommBus.txt
txt/03-23-2016audio_3 APCE-2015-3241-ZC-ZAA.txt
txt/03-23-2016audio_4 PubCom.txt
txt/03-23-2017audio_1 DirRpt.txt
txt/03-23-2017audio_2 CommBus.txt
txt/03-23-2017audio_3 NCP.txt
txt/03-23-2017audio_4 PubCom.txt
txt/03-23-2017audio_5a CPC-2004-6045 and 5b CPC-2016-4090.txt
txt/03-23-2017audio_6 CPC-2013-1595.txt
txt/03-23-2017audio_7 CPC-2016-2084.txt
txt/03-23-2017audio_8 CPC-2015-779.txt
txt/03-23-2017audio (Joint Meeting)_1 PubCom.txt
txt/03-23-2017audio (Joint Meeting)_2 CPC-2016-3390.txt
txt/03-24-2016_TRACK1.txt
txt/03-24-2016_TRACK2.txt
txt/03-24-2016_TRACK4.txt
txt/03-24-2016_TRACK5.txt
txt/03-24-2016_TRACK6.txt
txt/03-27-13audio_01DepartmentalReport.txt
txt/03-27-13audio_02CommissionBusiness.txt
txt/03-27-13audio_03ZA12-2955c.txt
txt/03-27-13audio_04ZA12-926c.txt
txt/03-28-2013audio_04CPC12-2405.txt
txt/03-28-2013audio_05VTT71837_CPC08-3440l.txt
txt/03-28-2017audio_1 DirRpt.txt
txt/03-28-2017audio_2 CommBus.txt
txt/03-28-2017audio_3 NCP.txt
txt/03-28-2017audio_4 DIR-2016-1692.txt
txt/03-28-2017audio_5 PubCom.txt
txt/04-05-2017audio_1 DirRpt.txt
txt/04-05-2017audio_2 CommBus.txt
txt/04-05-2017audio_3 NCP.txt
txt/04-05-2017audio_4 ZA-2016-2241.txt
txt/04-05-2017audio_5 ZA-2016-1587.txt
txt/04-05-2017audio_6 ZA-2015-2404.txt
txt/04-05-2017audio_7 PubCom.txt
txt/04-06-11audio_01DepartmentalReport.txt
txt/04-06-11audio_02CommissionBusiness.txt
txt/04-06-11audio_03APCW10-2193.txt
txt/04-06-11audio_04APCW10-3101b.txt
txt/04-06-11audio_05ZA10-129b.txt
txt/04-06-17 audio_1 DirRpt.txt
txt/04-09-2013audio_01DirectorsReport.txt
txt/04-09-2013audio_02CommissionBusiness.txt
txt/04-09-2013audio_03ZA12-1086.txt
txt/04-09-2013audio_04ZA12-520.txt
txt/04-09-2013audio_05ZA06-4238f.txt
txt/04-09-2013audio_06PublicCommentPeriod.txt
txt/04-10-2012audio_03APCC08-4700.txt
txt/04-10-2012audio_04ZA11-1763b.txt
txt/04-10-2012audio_05PublicCommentPeriod.txt
txt/04-11-2013audio_01DirectorsReport.txt
txt/04-11-2013audio_02CommissionBusiness.txt
txt/04-11-2013audio_03PublicCommentPeriod.txt
txt/04-11-2013audio_04CPC11-2157.txt
txt/04-11-2013audio_05CPC11-2480.txt
txt/04-11-2013audio_06CPC06-5567j.txt
txt/04-12-2011audio_01DIR10-2309b.txt
txt/04-12-2011audio_01DirectorsReport.txt
txt/04-12-2011audio_02CommissionBusiness.txt
txt/04-12-2011audio_03SPCC09-3510.txt
txt/04-12-2011audio_04PublicCommentPeriod.txt
txt/04-12-2012audio_01CPC11-2468.txt
txt/04-12-2012audio_02DirectorsReport.txt
txt/04-12-2012audio_03CommissionBusiness.txt
txt/04-12-2012audio_04DIR09-2065b.txt
txt/04-12-2012audio_05CPC11-2498.txt
txt/04-13-2016audio_1 DeptRpt.txt
txt/04-13-2016audio_2 CommBus.txt
txt/04-13-2016audio_3 AA-2015-1428-PMLA-1A.txt
txt/04-13-2016audio_4 PubCom.txt
txt/04-14-2011audio_01DirectorsReport.txt
txt/04-14-2011audio_02CommissionBusiness.txt
txt/04-14-2011audio_03PublicCommentPeriod.txt
txt/04-14-2011audio_04CPC09-3488c.txt
txt/04-14-2011audio_05CPC09-254.txt
txt/04-14-2011audio_06CPC10-1681.txt
txt/04-14-2011audio_07CPC09-2833.txt
txt/04-19-2017audio_1 DirRpt.txt
txt/04-19-2017audio_2 CommBus.txt
txt/04-19-2017audio_3 NCP.txt
txt/04-19-2017audio_4 Dir-2016-2028.txt
txt/04-19-2017audio_5 ZA-2016-2241.txt
txt/04-19-2017audio_6 PubComm.txt
txt/04-20-11audio_01DepartmentalReport.txt
txt/04-20-11audio_02CommissionBusiness.txt
txt/04-20-11audio_03APCW10-2349.txt
txt/04-20-11audio_04ZA06-5028e.txt
txt/04-20-17 audio_1 DirRpt.txt
txt/04-20-17 audio_2 CommBus.txt
txt/04-20-17 audio_3 NCP.txt
txt/04-20-17 audio_4 APCNV-2016-610.txt
txt/04-20-17 audio_5 APCNV-2015-3453.txt
txt/04-20-17 audio_6 PubCom.txt
txt/04-20-2017audio_1 DirRpt.txt
txt/04-20-2017audio_11 DIR-2016-304.txt
txt/04-20-2017audio_2 CommBus.txt
txt/04-20-2017audio_3 NCP.txt
txt/04-20-2017audio_4 PubCom.txt
txt/04-20-2017audio_5a CPC-2015-1479.txt
txt/04-20-2017audio_5b CPC-2016-4316.txt
txt/04-20-2017audio_6 CPC-2016-2863.txt
txt/04-20-2017audio_7-8 CPC-2015-4398 and CPC-2016-3681.txt
txt/04-20-2017audio_9-10 VTT-73536 and ZA-2015-1766.txt
txt/04-24-13audio_01DepartmentalReport.txt
txt/04-24-13audio_02CommissionBusiness.txt
txt/04-24-13audio_03ZA12-2587c.txt
txt/04-24-13audio_04PublicCommentPeriod.txt
txt/04-24-2012audio_01DirectorsReport.txt
txt/04-24-2012audio_02CommissionBusiness.txt
txt/04-24-2012audio_03DIR11-2751.txt
txt/04-24-2012audio_04PublicCommentPeriod.txt
txt/04-25-2013audio_01DirectorsReport.txt
txt/04-25-2013audio_02CommissionBusiness.txt
txt/04-25-2013audio_03PublicCommentPeriod.txt
txt/04-25-2013audio_04CPC09-837.txt
txt/04-25-2013audio_05CPC12-3243b.txt
txt/04-25-2013audio_06CPC10-3152_VTT61216f.txt
txt/04-25-2013audio_07CPC12-1363.txt
txt/04-25-2013audio_08CPC06-5569c.txt
txt/04-25-2017audio_1 DirRpt.txt
txt/04-25-2017audio_2 CommBus.txt
txt/04-25-2017audio_3 NCP.txt
txt/04-25-2017audio_4 ZA-2016-2478.txt
txt/04-25-2017audio_5 AA-2016-1474.txt
txt/04-25-2017audio_6 AA-2015-832.txt
txt/04-25-2017audio_7 DIR-2016-3612.txt
txt/04-25-2017audio_8 PubCom.txt
txt/04-26-2011audio_01DirectorsReport.txt
txt/04-26-2011audio_02CommissionBusiness.txt
txt/04-26-2011audio_03ZA10-09.txt
txt/04-26-2012audio_01DirectorsReport.txt
txt/04-26-2012audio_02CommissionBusiness.txt
txt/04-26-2012audio_03PublicCommentPeriod.txt
txt/04-26-2012audio_04CPC11-3238.txt
txt/04-26-2012audio_05CPC11-982.txt
txt/04-26-2012audio_06CPC07-1059d.txt
txt/04-26-2017audio_1 DirRpt.txt
txt/04-26-2017audio_2 CommBus.txt
txt/04-26-2017audio_3 NCP.txt
txt/04-26-2017audio_4 Dir-2016-3168.txt
txt/04-26-2017audio_5 PubCom.txt
txt/04-27-2016audio_1 DeptRpt.txt
txt/04-27-2016audio_2 CommBus.txt
txt/04-27-2016audio_3 ZA-2014-1597.txt
txt/04-27-2016audio_4 ZA-2015-838.txt
txt/04-27-2016audio_5 VTT-72779.txt
txt/04-27-2016audio_6 PubCom.txt
txt/04-27-2017audio_1 DirRpt.txt
txt/04-27-2017audio_2 CommBus.txt
txt/04-27-2017audio_3 NCP.txt
txt/04-27-2017audio_4 PubCom.txt
txt/04-27-2017audio_5a CPC-2016-2751.txt
txt/04-27-2017audio_6 CPC-2016-2865.txt
txt/04-27-2017audio_7-8 VTT-74583 and CPC-2016-4117.txt
txt/04-27-2017audio_9 CPC-2015-3028.txt
txt/04-28-2016_TRACK1.txt
txt/04-28-2016_TRACK2.txt
txt/04-28-2016_TRACK3.txt
txt/04-28-2016_TRACK4.txt
txt/05-02-2017audio_1 DirRpt.txt
txt/05-02-2017audio_2 CommBus.txt
txt/05-02-2017audio_3 NCP.txt
txt/05-02-2017audio_4 DIR-2015-1880.txt
txt/05-02-2017audio_5 PubCom.txt
txt/05-03-2016_TRACK1.txt
txt/05-03-2016_TRACK2.txt
txt/05-03-2016_TRACK3.txt
txt/05-03-2016_TRACK4.txt
txt/05-03-2017audio_1 DirRpt.txt
txt/05-03-2017audio_2 CommBus.txt

In [74]:
df

,case_name,CEQA,names,names_count,parking_mentions,affordability_mentions,community_mentions,num_words,num_nonstopgap_words,sentiment_pos,sentiment_neg,sentiment_neutral,date,area,txt_file_name
0,01DepartmentalRepor,NaN,[],0,1,0,0,203,122,0.256825,0.009197,0.733978,01-05-2011,West,txt/01-05-10audio_01DepartmentalReport.txt
1,02CommissionBusines,NaN,[],0,1,0,1,810,419,0.099221,0.269955,0.630824,01-05-2011,West,txt/01-05-10audio_02CommissionBusiness.txt
2,03ZA09-2885&04ZA09-2886,ENV-2009-2884-CE,"[(David, Carlat)]",1,9,0,3,9972,5145,0.064828,0.214557,0.720616,01-05-2011,West,txt/01-05-10audio_03ZA09-2885_04ZA09-2886b.txt
3,04ZA09-2886,NaN,[],0,0,0,1,496,278,0.059718,0.099156,0.841126,01-05-2011,West,txt/01-05-10audio_04ZA09-2886.txt
4,05APCW10-657,ENV-2009-2730-MND-REC1,"[(Melissa, Talber)]",1,0,0,0,917,509,0.143066,0.052420,0.804515,01-05-2011,West,txt/01-05-10audio_05APCW10-657.txt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2677,04PublicCommentPerio,NaN,[],0,0,0,0,16,8,0.126006,0.180575,0.693419,12-05-2012,West,txt/WLA12-05-12audio_04PublicCommentPeriod.txt
2678,01DepartmentalRepor,NaN,[],0,3,0,0,166,98,0.834490,0.003790,0.161720,12-07-2011,West,txt/WLA12-07-11audio_01DepartmentalReport.txt
2679,02CommissionBusines,NaN,[],0,0,0,0,106,69,0.177476,0.011594,0.810931,12-07-2011,West,txt/WLA12-07-11audio_02CommissionBusiness.txt
2680,03ZA11-1481,NaN,[],0,0,0,0,459,252,0.131128,0.075995,0.792877,12-07-2011,West,txt/WLA12-07-11audio_03ZA11-1481.txt
2681,04DIR10-2280,N,[],0,0,0,0,612,332,0.252628,0.041741,0.705631,12-07-2011,West,txt/WLA12-07-11audio_04DIR10-2280.txt

In [75]:
collapsed_df

,clean_file_name,case_name,audio_file_name
0,01-05-10audio,01DepartmentalRepor,[01-05-10audio_01DepartmentalReport]
1,01-05-10audio,02CommissionBusines,[01-05-10audio_02CommissionBusiness]
2,01-05-10audio,03ZA09-2885&04ZA09-2886,"[01-05-10audio_03ZA09-2885_04ZA09-2886a, 01-05..."
3,01-05-10audio,04ZA09-2886,[01-05-10audio_04ZA09-2886]
4,01-05-10audio,05APCW10-657,[01-05-10audio_05APCW10-657]
...,...,...,...
2677,WLA12-05-12audio,04PublicCommentPerio,[WLA12-05-12audio_04PublicCommentPeriod]
2678,WLA12-07-11audio,01DepartmentalRepor,[WLA12-07-11audio_01DepartmentalReport]
2679,WLA12-07-11audio,02CommissionBusines,[WLA12-07-11audio_02CommissionBusiness]
2680,WLA12-07-11audio,03ZA11-1481,[WLA12-07-11audio_03ZA11-1481]
2681,WLA12-07-11audio,04DIR10-2280,[WLA12-07-11audio_04DIR10-2280]

In [77]:
df.to_csv('cases.tsv', sep='\t',index=False)